name: example-environment

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.6
  - numpy
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - pip:
    - git+https://github.com/blaze/dask.git#egg=dask[complete]
